/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package subtitlesystemviews;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import subtitlesystemcontrollers.ClientController;
import subtitlesystemcontrollers.ServerController;

/**
 *
 * @author Mahmoud Aslan
 */
public class ServerViewer extends javax.swing.JFrame {

    
    
    private static int port;
    private static String fileName;
    private static String projMode;
    
    /**
     * Creates new form ClientControlViewer
     */
    public ServerViewer() {
        initComponents();
        port = 6666;
        projMode = "dup";
    }
    
    
    public static void setCurrentSubtitleLabel(String text) {
        labelCurrentSubtitle.setText("<html>" + text + "</html>");
    }
    
    public static void setNextSubtitleLabel(String text) {
        labelNextSubtitle.setText("<html>" + text + "</html>");
    }
    
    public static void setControlsState(boolean state) {
        buttonLoad.setEnabled(state);
        buttonPrevious.setEnabled(state);
        buttonNext.setEnabled(state);
        buttonDecreaseFont.setEnabled(state);
        buttonIncreaseFont.setEnabled(state);
        buttonDecreaseDimensionY.setEnabled(state);
        buttonIncreaseDimenstionY.setEnabled(state);
        buttonDecreaseDimensionX.setEnabled(state);
        buttonIncreaseDimenstionX.setEnabled(state);
        buttonTopPosition.setEnabled(state);
        buttonBottomPosition.setEnabled(state);
        buttonLeftPosition.setEnabled(state);
        buttonRightPosition.setEnabled(state);
        buttonCenterPosition.setEnabled(state);
    }
    
    public static String getProjMode() {
        return projMode;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonDecreaseFont = new javax.swing.JButton();
        buttonIncreaseFont = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelCurrentSubtitle = new javax.swing.JLabel();
        labelNextSubtitle = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        buttonPrevious = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        buttonLoad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonDecreaseDimensionX = new javax.swing.JButton();
        buttonIncreaseDimenstionX = new javax.swing.JButton();
        buttonDecreaseDimensionY = new javax.swing.JButton();
        buttonIncreaseDimenstionY = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        buttonTopPosition = new javax.swing.JButton();
        buttonBottomPosition = new javax.swing.JButton();
        buttonRightPosition = new javax.swing.JButton();
        buttonLeftPosition = new javax.swing.JButton();
        buttonCenterPosition = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Subtitle System");

        buttonDecreaseFont.setText("-");
        buttonDecreaseFont.setEnabled(false);
        buttonDecreaseFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecreaseFontActionPerformed(evt);
            }
        });

        buttonIncreaseFont.setText("+");
        buttonIncreaseFont.setEnabled(false);
        buttonIncreaseFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncreaseFontActionPerformed(evt);
            }
        });

        jLabel1.setText("Font Size :");

        jLabel2.setText("Subtitle File : ");

        labelCurrentSubtitle.setText("jLabel3");
        labelCurrentSubtitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelCurrentSubtitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Subtitle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 9), new java.awt.Color(153, 153, 153))); // NOI18N

        labelNextSubtitle.setText("jLabel3");
        labelNextSubtitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelNextSubtitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Next Subtitle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 9), new java.awt.Color(153, 153, 153))); // NOI18N

        labelInfo.setText("File Name");

        buttonPrevious.setText("< Previous");
        buttonPrevious.setEnabled(false);
        buttonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPreviousActionPerformed(evt);
            }
        });

        buttonNext.setText("Next >");
        buttonNext.setEnabled(false);
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Client Controls");

        jButton5.setText("About");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        buttonLoad.setText("Load Subtitle File");
        buttonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadActionPerformed(evt);
            }
        });

        jLabel3.setText("Dimensions :");

        jLabel4.setText("X :");

        jLabel5.setText("Y : ");

        buttonDecreaseDimensionX.setText("-");
        buttonDecreaseDimensionX.setEnabled(false);
        buttonDecreaseDimensionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecreaseDimensionXActionPerformed(evt);
            }
        });

        buttonIncreaseDimenstionX.setText("+");
        buttonIncreaseDimenstionX.setEnabled(false);
        buttonIncreaseDimenstionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncreaseDimenstionXActionPerformed(evt);
            }
        });

        buttonDecreaseDimensionY.setText("-");
        buttonDecreaseDimensionY.setEnabled(false);
        buttonDecreaseDimensionY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecreaseDimensionYActionPerformed(evt);
            }
        });

        buttonIncreaseDimenstionY.setText("+");
        buttonIncreaseDimenstionY.setEnabled(false);
        buttonIncreaseDimenstionY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncreaseDimenstionYActionPerformed(evt);
            }
        });

        jLabel6.setText("Position :");

        buttonTopPosition.setText("↑");
        buttonTopPosition.setEnabled(false);
        buttonTopPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTopPositionActionPerformed(evt);
            }
        });

        buttonBottomPosition.setText("↓");
        buttonBottomPosition.setEnabled(false);
        buttonBottomPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBottomPositionActionPerformed(evt);
            }
        });

        buttonRightPosition.setText("→");
        buttonRightPosition.setEnabled(false);
        buttonRightPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRightPositionActionPerformed(evt);
            }
        });

        buttonLeftPosition.setText("←");
        buttonLeftPosition.setEnabled(false);
        buttonLeftPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLeftPositionActionPerformed(evt);
            }
        });

        buttonCenterPosition.setText("↔");
        buttonCenterPosition.setEnabled(false);
        buttonCenterPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCenterPositionActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Extend");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Duplicate");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Projection Mode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(79, 79, 79)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(buttonDecreaseDimensionY)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(buttonIncreaseDimenstionY))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(buttonDecreaseDimensionX)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(buttonIncreaseDimenstionX))))
                                            .addComponent(jLabel3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonDecreaseFont)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonIncreaseFont)))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonLeftPosition)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(buttonBottomPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(buttonCenterPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(buttonTopPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonRightPosition))
                                    .addComponent(jLabel6))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelInfo)
                                .addGap(18, 18, 18)
                                .addComponent(buttonLoad))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCurrentSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNextSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(buttonNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelInfo)
                    .addComponent(buttonLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCurrentSubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(labelNextSubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPrevious)
                    .addComponent(buttonNext))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonDecreaseFont)
                                    .addComponent(buttonIncreaseFont)
                                    .addComponent(jLabel4)
                                    .addComponent(buttonDecreaseDimensionX)
                                    .addComponent(buttonIncreaseDimenstionX))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonDecreaseDimensionY)
                                    .addComponent(buttonIncreaseDimenstionY)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(buttonTopPosition)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonCenterPosition)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBottomPosition))
                                    .addComponent(buttonLeftPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonRightPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))
                            .addComponent(jButton5))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIncreaseFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncreaseFontActionPerformed
        ServerController.sendCommandToClient("font", "true");
    }//GEN-LAST:event_buttonIncreaseFontActionPerformed

    private void buttonDecreaseFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecreaseFontActionPerformed
        ServerController.sendCommandToClient("font", "false");
    }//GEN-LAST:event_buttonDecreaseFontActionPerformed

    private void buttonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPreviousActionPerformed
        ServerController.preSubtitle();
    }//GEN-LAST:event_buttonPreviousActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(null, "This software was originally created to help making TedxMimasStreet main event talks more accessible to the foreign audience. \nWebsite: future link\nGithub repo : future link", "Info", 1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void buttonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadActionPerformed
        JFileChooser fileChooser = new JFileChooser();
            if(fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                try {
                    ServerController.readFile(file.getAbsolutePath());
                    labelInfo.setText(file.getName());
                } catch (IOException ex) {
                }
            }
    }//GEN-LAST:event_buttonLoadActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        ServerController.nextSubtitle();
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonDecreaseDimensionXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecreaseDimensionXActionPerformed
        ServerController.sendCommandToClient("dimx", "false");
    }//GEN-LAST:event_buttonDecreaseDimensionXActionPerformed

    private void buttonDecreaseDimensionYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecreaseDimensionYActionPerformed
        ServerController.sendCommandToClient("dimy", "false");
    }//GEN-LAST:event_buttonDecreaseDimensionYActionPerformed

    private void buttonIncreaseDimenstionYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncreaseDimenstionYActionPerformed
        ServerController.sendCommandToClient("dimy", "true");
    }//GEN-LAST:event_buttonIncreaseDimenstionYActionPerformed

    private void buttonIncreaseDimenstionXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncreaseDimenstionXActionPerformed
        ServerController.sendCommandToClient("dimx", "true");
    }//GEN-LAST:event_buttonIncreaseDimenstionXActionPerformed

    private void buttonBottomPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBottomPositionActionPerformed
        ServerController.sendCommandToClient("posy", "bottom");
    }//GEN-LAST:event_buttonBottomPositionActionPerformed

    private void buttonTopPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTopPositionActionPerformed
        ServerController.sendCommandToClient("posy", "top");
    }//GEN-LAST:event_buttonTopPositionActionPerformed

    private void buttonRightPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRightPositionActionPerformed
        ServerController.sendCommandToClient("posx", "right");
    }//GEN-LAST:event_buttonRightPositionActionPerformed

    private void buttonLeftPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLeftPositionActionPerformed
        ServerController.sendCommandToClient("posx", "left");
    }//GEN-LAST:event_buttonLeftPositionActionPerformed

    private void buttonCenterPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCenterPositionActionPerformed
        ServerController.sendCommandToClient("posx", "center");
    }//GEN-LAST:event_buttonCenterPositionActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        ServerController.sendCommandToClient("proj", "ext");
        projMode = "ext";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        ServerController.sendCommandToClient("proj", "dup");
        projMode = "dup";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerViewer().setVisible(true);
            }
        });
        
        FileReader fr;
        try {
            fr = new FileReader("./SubXServer.ini");
            BufferedReader br = new BufferedReader(fr);
            String configurationLine;
            try {
                while((configurationLine = br.readLine()) != null) {
                    String[] values = configurationLine.split("=");
                    for(int i = 0 ; i < values.length ; i+=2) {
                        String key = values[i].trim();
                        String value = values[i+1].trim();
                        switch(key) {
                            case "port" :
                                port = Integer.parseInt(value);
                                break;
                            case "defaultFile" :
                                fileName = value;
                                break;
                            default:
                                break;
                        }
                    }
                }
            } catch(IOException | NumberFormatException e ) {
            }
        } catch (FileNotFoundException ex) {
            //Set label text to not found!
            System.out.println("FILE NOT FOUND");
        }
       
       ServerController server = new ServerController(port, fileName);
       new Thread() {
           @Override
           public void run() {
               server.create();
           }
       }.start();
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton buttonBottomPosition;
    private static javax.swing.JButton buttonCenterPosition;
    private static javax.swing.JButton buttonDecreaseDimensionX;
    private static javax.swing.JButton buttonDecreaseDimensionY;
    private static javax.swing.JButton buttonDecreaseFont;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private static javax.swing.JButton buttonIncreaseDimenstionX;
    private static javax.swing.JButton buttonIncreaseDimenstionY;
    private static javax.swing.JButton buttonIncreaseFont;
    private static javax.swing.JButton buttonLeftPosition;
    private static javax.swing.JButton buttonLoad;
    private static javax.swing.JButton buttonNext;
    private static javax.swing.JButton buttonPrevious;
    private static javax.swing.JButton buttonRightPosition;
    private static javax.swing.JButton buttonTopPosition;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JLabel labelCurrentSubtitle;
    private javax.swing.JLabel labelInfo;
    private static javax.swing.JLabel labelNextSubtitle;
    // End of variables declaration//GEN-END:variables
}
